### ISSUE TITLE
jbiginteger not found

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire-seedbox-daemon#3]
When I start the programm I get
```
INFO 24936 --- [ main] net.i2p.util.NativeBigInteger : Resource name [libjbigi-linux-none_64.so] was not found
INFO 24936 --- [ main] net.i2p.util.NativeBigInteger : Resource name [libjbigi-linux-none.so] was not found
WARN 24936 --- [ main] net.i2p.util.NativeBigInteger : Native BigInteger library jbigi not loaded - using pure Java - poor performance may result - see http://i2p-projekt.i2p/jbigi for help
```

i2p (separate installation) shows in its logs that it uses jbigi, libjbigi.so and
libjcpuid.so are in its directory. In the webfrontend of i2prouter seedbox is listed under tunnels and has a green dot so it uses this i2prouter as it should.

**Comment by zlatinb** [comment]
That is an error message from the i2p library, which makes the assumption that it will always be used as part of a router.  But the seedbox daemon does not include a router, so it is nothing to worry about.

**Comment by JamesOlvertone** [comment]
Ok, thx.
